### ISSUE TITLE
Reset App Settings

### ISSUE THREAD

**Issue by kyliefk** [willowtreeapps/eyespeak-ios#114]
**As a vocable app (iOS) user, I would like to be able to reset the app to the default settings**

**As a tester, when automating I would like to be able to trigger the reset functionality in my test code so that I do not need to randomize category names and phrases.**

**Designs**
NEEDED

For Automated Testing:
We would like to be able to trigger this reset at the launch of the app so we don't need to randomize our test data; e.g. category names. This should be an environment variable flag.

**Acceptance Criteria**
- Users can tap on the Settings > 'Reset App Settings' button to reset the app to the original default settings and content.
- An environment variable flag exists that can be set from within UI test code so we can reset the app data during testing.

**Comment by rhsalas3** [comment]
@Clstroud 

Per our conversation about using random strings in test code. I have updated this ticket to include our solution; the environment variable flag.
