### ISSUE TITLE
Keyboard function key icons cut off on iPhone

### ISSUE THREAD

**Issue by jsmorgan42** [willowtreeapps/eyespeak-ios#123]
The keyboard function keys' icons on iPhone are cut off within the cell.

![IMG_0557](https://user-images.githubusercontent.com/37670742/76427088-44d61300-6382-11ea-9f18-75beaeb65f50.PNG)
![IMG_0556](https://user-images.githubusercontent.com/37670742/76427709-0725ba00-6383-11ea-8982-4a35e16b0394.PNG)

**Comment by Ly-Kyli** [comment]
@SashankPatel Maybe QA can retest to ensure it's still relevant?

**Comment by SashankPatel** [comment]
Closing this out.  Tested on simulator with iPhone 12 and iPhone SE and the buttons are not cutoff with v1.4.x.  If seen again a new bug will be created.
![Screen Shot 2022-05-10 at 3 34 05 PM](https://user-images.githubusercontent.com/50410188/167708540-90395d45-0dfa-4be0-8d0a-def1c01fd012.png)
![Screen Shot 2022-05-10 at 3 33 52 PM](https://user-images.githubusercontent.com/50410188/167708541-f1de7ac2-ac28-46df-8239-18e6ec6db6ce.png)
.
