### ISSUE TITLE
Add toast message when saving edit for a saying

### ISSUE THREAD

**Issue by jsmorgan42** [willowtreeapps/eyespeak-ios#146]
When confirming & saving the edit for a saying, there should be a toast message saying that the "Changes saved"

<img width="553" alt="Screen Shot 2020-03-18 at 10 14 43 AM" src="https://user-images.githubusercontent.com/37670742/76969986-8ece7400-6901-11ea-907c-c77953c11c8c.png">

**Comment by Clstroud** [comment]
This will require some restructuring to make presentable in multiple contexts, and should likely encompass the work defined in #153
