### ISSUE TITLE
Update toast notification to match designs

### ISSUE THREAD

**Issue by Clstroud** [willowtreeapps/eyespeak-ios#153]
* Add blur/visual effect view to the background
* Add an icon to reinforce the message
<img width="407" alt="Screen Shot 2020-03-20 at 9 46 27 AM" src="https://user-images.githubusercontent.com/143916/77169340-b4898380-6a8f-11ea-8866-729c018d9780.png">
<img width="198" alt="Screen Shot 2020-03-20 at 9 46 33 AM" src="https://user-images.githubusercontent.com/143916/77169343-b5221a00-6a8f-11ea-82a4-831d098288f8.png">

**Comment by jennydoesthings** [comment]
This toast is no longer relevant.
