### ISSUE TITLE
Add message to display head tracking not supported for older devices

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/eyespeak-ios#204]
**Acceptance Criteria**
For users trying to use the app in older devices, we will add message to display that head tracking is not supported for older devices

**Comment by pg8wood** [comment]
[Current designs](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=1%3A1344) disable the "head tracking" switch in settings on unsupported devices. 

Will need designs around when to show this message (when attempting to enable head tracking on an unsupported device, once @ first app launch, within onboarding, etc.)

**Comment by SashankPatel** [comment]
Footer text has been added in the Selection Mode screen noting why the head tracking button is disabled and why the iPad is not supported in version 1.4.0.  If we want to enhance this feature then we can create a separate ticket.
