### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by Uma-mv** [willowtreeapps/eyespeak-ios#217]
Acceptance Criteria:
- any scenarios or conditions that need to be satisfied
- list out criteria maybe in gherkin format if it seems fit

Design:
- Screenshots
- Link

**Comment by Ly-Kyli** [comment]
@SashankPatel We have templates when we create tickets now. Are these still needed?

**Comment by SashankPatel** [comment]
We already have templates as part of the github repo.
