### ISSUE TITLE
Selected category should update when paginating on iPhone portrait

### ISSUE THREAD

**Issue by jsmorgan42** [willowtreeapps/eyespeak-ios#233]
On iPhone portrait within the main preset screen, when a user either uses a category pagination button or swipe to the left or right on the categories scroll view, the category the user lands on should automatically be selected.

This will have to be a special case on when using the iPhone portrait orientation since there is only one category within the category collection view at a time.

**Comment by jennydoesthings** [comment]
The correct behavior is currently in the app.
