### ISSUE TITLE
Alert Modal Background Revisions - Design Updates

### ISSUE THREAD

**Issue by okayce** [willowtreeapps/eyespeak-ios#248]
![modal background looks hidden](https://user-images.githubusercontent.com/62388550/80132751-24e16400-856a-11ea-8fc4-ec7e2e5e3d4d.jpg)

When there is no content on screen alert modals backgrounds are the same color as the app background. 

- [ ] Design: Change layouts and alert team.
- [ ] Change all instances of alert modals with new backgrounds.

**Comment by Ly-Kyli** [comment]
@SashankPatel We updated this recently.

**Comment by SashankPatel** [comment]
Closing this ticket out, per latest design updates this enhancement is superseded by: #493
