### ISSUE TITLE
Delete phrases from a custom category

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/eyespeak-ios#334]
**As a user, I need the ability to delete a custom phrase from a custom category so that I can manage what's available.**

**AC:**
1. User can delete all custom phrases from a custom category but only individually.
2. Users should be presented with a confirmation modal before deletion is completed. 
3. Deleted phrases cannot be recovered for now

**Designs:**
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by SashankPatel** [comment]
Implemented on PR391
