### ISSUE TITLE
Add Phrases to Custom Category

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/eyespeak-ios#335]
**As a user, I would like the ability to create new phrases inside of my custom category so that I may use them from the main screen of Vocable**

Acceptance criteria:

1. To access custom phrases, a user will navigate to the "Categories and Phrases" screen in Settings. Custom categories will have an additional detail screen (accessed by the right arrow) where they will have an option to add new phrases.
2. Custom phrases are unique entities and identical phrases can exist in multiple categories. Deleting or editing an identical phrase from one category does not remove it or edit it in another category.
3. Clicking the "add" button will begin the add/edit keyboard flow. If users exit the keyboard without saving, a discard progress alert will be triggered.
4. User can add phrases to the custom category from the custom category flow, or from the keyboard "add" button.

Implementation Note: Successful save notification will need to be updated. Currently if a phrase is added to a custom category notification says "Saved to My Sayings" but it was actually saved to the custom category. Note when a new category is added the notification says "Changes saved", we may want to use this generic message instead.

Test Note:
Custom Phrases will be in English only as of this ticket.

Designs:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by SashankPatel** [comment]
Implemented on PR391
