### ISSUE TITLE
Edit Phrases in a Custom Category

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/eyespeak-ios#336]
**As a user, I need the ability to edit existing custom phrases to maximize the customization of my experience.**

**AC**
1. User will have the ability to view existing phrases within the custom category and enter an edit flow to update the phrase
2. Leaving the flow without changes should allow the user to exit without a warning
3. Attempting to exit without saving changes should prompt the user to save those changes. 

Designs:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by SashankPatel** [comment]
Implemented on PR391
