### ISSUE TITLE
Update Alert Modal Background Color

### ISSUE THREAD

**Issue by hlargen5** [willowtreeapps/eyespeak-ios#357]
When there is no content on screen alert modals backgrounds are the same color as the app background. This is now updated in the design file.

Acceptance criteria:

- All alert modal backgrounds should be changed to #504B93 at 85% opacity (currently they are #201C5B).
- Alert modal backgrounds are shown anytime changes are made to custom categories and phrases (creating a new category/phrase, editing a category/phrase, and removing category/phrase. This update should be reflected globally.

Link to Figma:

Keyboard Edits:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A700

Custom Category/Phrases:
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by Ly-Kyli** [comment]
@SashankPatel We just did an alert as well as toast design update. This ticket is probably obsolete.

**Comment by SashankPatel** [comment]
Closing out this ticket...this ticket is superceded by #494.
