### ISSUE TITLE
Remove "My Sayings" Category

### ISSUE THREAD

**Issue by hlargen5** [willowtreeapps/eyespeak-ios#358]
**Acceptance Criteria**:

- ~~"My Sayings" category should be removed from the Home Screen. (See the comments below)~~
- ~~"My Sayings" category and detail screen should be removed from the "Categories" page in the Settings screen.~~ (See comments below)
- The "Edit My Sayings" page should be removed from the Settings screen.

**Design (Home Screen):**
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A141

**Design (Settings Screen):**
https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by stevefosterwta** [comment]
After a review we decide that we will not remove the `My Sayings` category to preserve any My Sayings phrase created by current users. 

With the release of custom categories users will be able to edit the `My Sayings` category name and also hide the My Sayings category. However the user will not be able to delete the entire `My Sayings` as is possible with the new custom categories.
