### ISSUE TITLE
Automation - Test My Sayings pagination on Home screen

### ISSUE THREAD

**Issue by pg8wood** [willowtreeapps/eyespeak-ios#382]
**Acceptance Criteria**:
Given I am on the Home screen and I add enough sayings to fill up the screen
Then the pagination button shall become enabled and take me to the next page of My Sayings and the pagination text displays the new number of pages

**Design**:
https://www.figma.com/file/0XCO0RWFIa2ckp81SXoqNSLa/Vocable?node-id=1874%3A1

Note: these tests should be run on the iPhone simulator

**Comment by SashankPatel** [comment]
Automation testing was implemented in PR399.  Since my sayings is going away, added the testing to the custom categories.
