### ISSUE TITLE
Edit/Delete Custom Category

### ISSUE THREAD

**Issue by stevefosterwta** [willowtreeapps/eyespeak-ios#390]
- To edit a custom category name, the user will navigate to the category detail screen and tap the pencil icon. This will take them into the edit keyboard flow.
- If a user closes the keyboard without saving any changes, they should receive the discard edits alert.
- If a user does not make any changes and closes the keyboard, no alert should be given.
- To delete an entire category, a user should navigate to the custom category detail screen and tap the trash can icon in the top right-hand corner. This will delete the entire category and all of its custom phrases in both the Categories setting screen and the home screen.
- A user should receive the "are you sure you want to delete?" alert when tapping the delete category button. 

**Design**:

https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable-New?node-id=1%3A1344

**Comment by pg8wood** [comment]
@stevefosterwta We're triaging the custom category tickets. Can you review the AC and let us know if anything is duplicated by other tickets?

**Comment by CananArikan** [comment]
Hi @SashankPatel, @rhsalas3 and I looked at the AC and design. We confirmed on develop branch for an ipad and iphone. We think this one is ready for development.

**Comment by SashankPatel** [comment]
Removed the following AC and moved it to ticket #461.  
If a user names the category after a pre-existing category, we should present error messaging notifying them: "Sorry, this Category name already exists. Please try a different name" with the option of "OK".

The rest of the AC's are implemented in build 1.4.7-1760 so therefore marking this as complete.
