### ISSUE TITLE
Users can Create 1 or more New Categories from the New Category Flow

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/eyespeak-ios#397]
As a user, I'd like the ability to create more than one new category so that I do not have to return to the main screen after each.  i.e. When creating new custom categories the keyboard should remain visible so that I can enter more category names.

- Should current category title clear?
- Custom Category names are still checked to avoid duplicates. (this work will be completed with issue #461 )

**Comment by CananArikan** [comment]
Hi @SashankPatel, @rhsalas3 and I looked at the AC and design. We think this needs a design review still.

**Comment by CananArikan** [comment]
@SashankPatel, after we add one new category from the new category keyboard, should we go back to list of Categories or remain on the keyboard? When we refer "Main screen" as it is written in this ticket, does that mean the list of categories or the Home Screen?

**Comment by SashankPatel** [comment]
@CananArikan: Good question, I would interpret Main screen as the Home screen, but we can reword to say that it just remains on the keyboard view.  The intent of this is the ability to add more than 1 category so you after adding a category the keyboard would stay visible so you can add more if you wanted.  Agree the design needs review.

**Comment by rhsalas3** [comment]
This ticket/issue cannot be completed as written without implementing #461 first. This is because the criteria for preventing duplicate categories has not been implemented yet. 

For reference, the original ticket for Edit/Delete custom categories: #390

**Comment by SashankPatel** [comment]
This ticket is under Design review to see if we want the ability to create custom categories from the Keyboard screen.

**Comment by SashankPatel** [comment]
Closing this out for the time being.  We will monitor user feedback and revisit in the future if there is a need.  There may be a better way to do this.
