### ISSUE TITLE
How to explanation for voice feature

### ISSUE THREAD

**Issue by kyliefk** [willowtreeapps/eyespeak-ios#435]

**Comment by Ly-Kyli** [comment]
@SashankPatel I think this can be closed since we have a ticket where we explained listen mode and hey vocable in settings.

**Comment by SashankPatel** [comment]
Closing this out.  There is an explanation in both the Settings screen as to what the toggles do as well as some footer text in the Listen mode category.  If further explanation is needed a new ticket will be created with details.
