### ISSUE TITLE
Vocable iOS - Custom Category tile highlighting on Home screen.

### ISSUE THREAD

**Issue by SashankPatel** [willowtreeapps/eyespeak-ios#463]
**Device Information**
Seen on an iPad 7th Gen with iOS 14.

**Describe the bug**
On the Home screen in the area where you can select categories, there is some inconsistent highlighting.

**To Reproduce**
This was seen on the a
1. Launch the app
2. Create a custom category if there arn't any.
3. Navigate back to the home screen.
4. Tap on the Listen category -> Category tile should be highlighted.
5. Tap on the new Custom Category next to the Listen <- ISSUE 1
6. Tap on the add phrase button and add a new phrase. <- ISSUE 2

**Expected behavior**
Listen should unhighlight and the custom category tile should highlight.
After a phrase is added from the main screen the custom category and phrase should be visible.

**Actual behavior**
Both the Listen and Custom Category tiles are highlighted.
This also happens with General, if you tap General and then the Custom category both will be highlighted.
After a phrase is added, instead of showing the custom category and newly added phrase, the Listen/General tab is displayed.

**Screenshots**
![IMG_0032](https://user-images.githubusercontent.com/50410188/157957313-1847fab7-6aca-40c9-817d-9516679c2966.PNG)

**Comment by rhsalas3** [comment]
Per my update to [the comment](https://github.com/willowtreeapps/vocable-ios/pull/491#issuecomment-1076243145) left on PR #491 (to implement feature #253 ):

Here is the recording of the additional behavior noted, whereby the custom category is not automatically selected as a user scrolls to it on an iPhone in Portrait. Also in this recording, while in Landscape the behavior captured in this bug issue is demonstrated.

Simulator - iPhone 12 - iOS 15.4 - from branch `feature/253/categories-sayings-empty-state`

https://user-images.githubusercontent.com/34660497/159769895-a48d9c47-de73-449b-9900-aa67980d0771.mp4

**Comment by SashankPatel** [comment]
Verified on iOS 14 and 15, this but seems to no longer occur on 1.4.0-2485.  Verified on iPhone 12 and iPad 7th gen.  Closing out the bug.
