### ISSUE TITLE
Make categories and phrases universally editable

### ISSUE THREAD

**Issue by Clstroud** [willowtreeapps/eyespeak-ios#465]
Using the existing UI implementation (for now), a user should be able to *rename* and *remove* all categories and phrases. The current implementation restricts these actions to custom, user-defined categories and phrases.

**Comment by SashankPatel** [comment]
Verified Phrases can now be removed from preset categories and empty state appears.
- ISSUE: Categories can not be removed.

**Comment by rowildcard** [comment]
Rudy -> Testing on the Simulator - iPad 9th Generation - 15.4

**Acceptance Criteria**
- [x] Custom phrases should behave as before. 
- [x] The user can rename a preset category.
- [x] The user can rename a preset phrase. 
- [x] The user can delete all preset categories except My Sayings .
- [x] The user can delete a preset phrase. 
- [x] The user can delete all phrases in a preset category except from the following categories: "123" and "Recent'
- [x] The user can delete all preset phrases.
- [x] The user shall not be able to add phrases to the "Listen" category
- [x] The user shall not be able to add phrases to the "123" category
- [x] The user shall be able to Show/Hide all preset and custom categories except "My Sayings" and "Listen"

**Test Scenarios**
- [x] After making changes to presets, the user force quits the app and relaunches.
- [x] After making changes to presets, the user changes languages and relaunches the app. 
- [x] The app is updated.
- [x] Ensure the initially-selected category on the main screen can be removed by the user.  I.e. Select a category on the main screen and delete that category from settings.
- [x] Ensure that the up/down controls on the Settings -> Edit Categories screen were updated properly after a category is deleted

**Test Plan**
Verify each AC under each of the scenarios. 
E.g. Verify when the user renames a preset category the rename persists after relaunching the app.

**Comment by rowildcard** [comment]
Testing on iPad (9th gen) iOS 15.1

**Acceptance Criteria**
- Custom phrases should behave as before. ✅ 
- The user can rename a preset category. ✅ 
- The user can rename a preset phrase. ✅ 
- The user can delete a preset category. ✅ 
- The user can delete a preset phrase. ✅ 
- The user can delete all phrases in a preset category. ✅ 
- The user can delete all preset categories (except for "My Sayings" and "Listen"). ✅ 

**Test Scenarios**
- After making changes to presets, the user force quits the app and relaunches. ✅ 
- After making changes to presets, the user changes languages and relaunches the app. **(out of scope).** 
- The app is updated. ✅ 

**Test Plan**
Verify each AC under each of the scenarios. 
E.g. Verify when the user renames a preset category the rename persists after relaunching the app.

**Comment by rhsalas3** [comment]
Tested and verified on the PR branch (#471 ) to be working as expected.
