### ISSUE TITLE
Custom Categories Design Updates

### ISSUE THREAD

**Issue by sgordon1024** [willowtreeapps/eyespeak-ios#472]
#### Design - Custom Categories
Allow the user to add custom categories and edit existing ones.

- [x] Review current designs
- [x] Update current designs
- [x] Prototype new designs
- [x] Review new designs

---

**Updates**
- Initially matched the functionality of build to designs
- Keeping "My Sayings" as a quick way to add favorites
- All categories except "Frequent" will be editable
- "My Sayings" title cannot be changed
- If a user has updated a category, they will not get future updates. If they haven't they'll continue to receive updates to that category. - Check with dev team on this
- Added an edit button to the category page so the user can quickly get to category settings.

**Comment by Ly-Kyli** [comment]
@SashankPatel Past design for this as well. This can be closed?

**Comment by SashankPatel** [comment]
Custom Categories has been released in version 1.4.0.
