### ISSUE TITLE
Update Category Buttons

### ISSUE THREAD

**Issue by sgordon1024** [willowtreeapps/eyespeak-ios#474]
#### Design - Category Button
Change the category buttons to be a single button.

- [ ] Update all layouts to match new style
- [ ] Review with team

**Why?**
- increases the hit area for these buttons
- we can reuse already existing buttons

**Comment by Ly-Kyli** [comment]
@SashankPatel This can probably be closed since we are past design for this feature/

**Comment by SashankPatel** [comment]
Closing this out as as custom categories was release in iOS version 1.4.  Button hit area was increased.
