### ISSUE TITLE
Update Layout in the Phrases view based on designs

### ISSUE THREAD

**Issue by SashankPatel** [willowtreeapps/eyespeak-ios#476]
**Acceptance Criteria**:
No Functional changes.
- As a user I shall be able to delete phrases.
- As a user I shall be able to edit phrases
- As a user I shall be able to add new phrases.
- As a user I shall be able to scroll through multiple pages of phrases

The layout on the Edit Phrase view has updated.  The delete confirmation button should be red. This ticket is to make updates to the existing UI to implemented the design updates.

**Design**:
iPad Landscape: https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=969%3A1629
iPad Portrait: https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3398%3A19036
iPhone: https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3356%3A17664

**Comment by rhsalas3** [comment]
Tested and confirmed on Jesse's PR branch for this issue; PR #496 

Layout matches designs and there are no regressions on functionality. I confirmed this for preset and custom categories/phrases.
