### ISSUE TITLE
Update Edit Category Screen Styling

### ISSUE THREAD

**Issue by Ly-Kyli** [willowtreeapps/eyespeak-ios#485]
**Acceptance Criteria**:
1. Pencil Icon is now replaced with the rename category button
2. "Show" is renamed as "Show Category"
3. Edit Phrases styling updated to match other buttons (currently text is smaller than other buttons on this screen)
4. Remove Category button color and styling updated
5. Margins and padding updated to match figma design

**Design**:
[Tablet Landscape](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3428%3A27794)
[Tablet Portrait](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3356%3A18141)
[Iphone Landscape](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3356%3A18013)
[Iphone Portrait](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3356%3A17831)

**Comment by rhsalas3** [comment]
@CananArikan and I tested the changes on the PR branch for this ticket (#527 ). The screen matches designs and meets the ACs, and continues to function as expected. So this issue looks good to go.

We did have some feedback about the way the buttons look now, when they're in the disabled state. This was written up as a new issue ticket, #531 .
