### ISSUE TITLE
Head Tracking Does Not Work On iPhone 8 Plus - iOS 14.8.1

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#488]
**Describe the bug**
It is expected that Apple devices that are able to run iOS 14.x will be able to utilize head tracking for the app. With an iPhone 8 Plus (model #MQ8D2LL/A) that has an A11 Bionic processor, the Vocable app does not allow for head tracking.

The version of the app under test is 1.4.0-1760 (from TestFlight).

Update: Could be the source of the issue stems from the device not asking for permission to use the camera. On a fresh install, it is expected that Vocable asks for camera access, but this is not happening on the iPhone 8 Plus under test.

**To Reproduce**
1. Install and launch the Vocable app.
2. Note that, at launch, there is no alert prompting for camera access.
3. From the Main Screen > tap the Settings button
4. tap on 'Selection Mode' 
5. tap on the 'Head Tracking' toggle switch

**Expected behavior**
The 'Head Tracking' toggle switch should be enabled, and tapping it will toggle on/off the head tracking feature.

**Actual behavior**
The 'Head Tracking' toggle switch is disabled.

**Device Information**
 - Device: iPhone 8 Plus
 - OS: 14.8.1
 - Model #: MQ8D2LL/A

Neural Engine Version History -> https://apple.fandom.com/wiki/Neural_Engine
iPhone Devices w/ Neural Engines -> https://apple.fandom.com/wiki/List_of_Apple_processors#A_series

**Comment by rhsalas3** [comment]
@Clstroud 

Added this bug issue based on our conversation about whether or not my iPhone 8 Plus test device should expect to be able to use head tracking.

CC: @SashankPatel  @moyerr @jsmorgan42

**Comment by SashankPatel** [comment]
Latest update, the device doesn't support head tracking.  Instead of closing out this bug, we decided to add footer text to noting device is not support.
