### ISSUE TITLE
Custom Category: Update Styling for Alert Messages

### ISSUE THREAD

**Issue by Ly-Kyli** [willowtreeapps/eyespeak-ios#494]
An alert currently appears when a user make edits to category name/phrases but does not save and when they delete a phrase or click remove category. 

**Acceptance Criteria:**
- All alerts have the same styling below
- Alert Background is F2F2F2 at 80%
- Alert overlay is 40% black 
- Alert overlay button colors are updated to "background purple" and "error red". (Currently it is Black)
- Screen behind alert is blur 10
- Destructive option (Discard, Remove) on the alert is moved to the right side. (Currently it is on the left)
- Update wording of alert message when a user make edits to a category name but chooses to exit without saving.
- Update wording of alert message when a user make edits to a phrase but chooses to exit without saving.
- Update wording of alert message when user chose to delete phrase. 

Design:

1. [Category Changes without Saving Alert](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=989%3A254)
2. [Phrase  Changes without Saving Alert](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=988%3A16073)
3. [Delete Phrase Alert](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=969%3A2216)
4. [Remove Category Alert](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3428%3A27980)

**Comment by rhsalas3** [comment]
Since this PR branch is based off of another branch that has known issues, we will wait to test these changes when the [dependency branch/PR](https://github.com/willowtreeapps/vocable-ios/issues/530) is 'test verified' and merged into this one.
