### ISSUE TITLE
Accessibility: Update Speak Button on Keyboard to Primary Purple

### ISSUE THREAD

**Issue by Ly-Kyli** [willowtreeapps/eyespeak-ios#522]
Currently the speak button on the keyboard is "action blue" with a white icon but the white icon does not pass accessibility. 

**Acceptance Criteria**:

- Update speak button icon from white to primary purple

**Design**:

[Keyboard
](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=988%3A6155)

**Comment by rhsalas3** [comment]
@rowildcard is testing the PR associated with this issue, so I updated the label.
