### ISSUE TITLE
Voice UI: User Can See Additional Information When Sharing Data for Listen Mode

### ISSUE THREAD

**Issue by Ly-Kyli** [willowtreeapps/eyespeak-ios#561]
**User Story:** As a user, I want to understand what data I am sharing with app developers so that I can choose if I want to share my data or not.

**Acceptance Criteria**:
- When any user is on the Listen mode, there is an information icon next to the option to share data that the user can select to see additional details about what is being sent
- **Button styling:**
  - Background color is Primary Purple
  - Font Color is D1EEE9
- **Selection State:**
  - Background color is Active Green
  - Font Color is Primary Purple
- **Information Modal:** 
  - Once the button is clicked, user gets a modal that informs them about the data that could be shared 
     - **MODAL COPY:** Anonymously sharing the question that was just asked will help us offer a better selection of 
           responses in the future.
                                     “What is your name?”
  - User has the option "Continue to Share" or "Cancel" 
  - If the user chose to send, a confirmation that the question was shared replaces the "Share" button
  - There is a checkmark icon next to confirmation text
    - Checkmark background color is Active Green
    - Checkmark color is Primary Purple
 

**Design**:
- [Information Modal Tablet](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=4213%3A23089)
- [Information Modal Mobile](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=4213%3A24673)

**Comment by jsmorgan42** [comment]
This issue is no longer needed after a design refinement was made to only have hint text instead of an info alert.
