### ISSUE TITLE
Categories List Screen | Last Category Down Button Is Not Disabled

### ISSUE THREAD

**Issue by CananArikan** [willowtreeapps/eyespeak-ios#602]
**Description:**
In the categories list screen, last category (8th) down button is not disabled (SS1). But, when we add a custom category as 9th category, last category down button is disabled (SS2). If we remove last (9th) custom category and having totally 8 categories, last category down button is not disabled (SS3). If we add a custom category and remove a preset category, last category down button is disabled (SS4). 

**Steps To Reproduce:**

1. Go to the `Settings`
2. Select `Categories and Phrase`
3. Add a custom category
4. Remove last custom category
5. Add a custom category
6. Remove a preset category

**Expected behavior:**
Last category down button is disabled.

**Actual behavior:**
Last category down button is not disabled.

**Device Information:**
iPad Pro - Test Device - iOS 15.3.1

**Build:**
1.4.0 - 2369 (TestFlight)

**Screenshots:**
**SS1**
![SS1_CategoriesListLastDownButtonIsNotDisabled](https://user-images.githubusercontent.com/100222793/165386803-aaa87a91-b715-4ea5-9929-c4b8d30d780b.PNG)
**SS2**
![SS2](https://user-images.githubusercontent.com/100222793/165388731-f6cccba5-4ba2-4a97-bf88-e242d92f773a.PNG)
**SS3**
![SS3](https://user-images.githubusercontent.com/100222793/165388758-8c523131-09c1-476a-a76a-67ad6f7db6a6.PNG)
**SS4**
![SS4](https://user-images.githubusercontent.com/100222793/165388769-45bf8e15-2841-4f56-9aee-306eafc4f9e8.jpeg)

**Comment by SashankPatel** [comment]
Decided to fix for 1.4.
Fix will be branched off develop and cherry picked into release/1.4.
