### ISSUE TITLE
Disabled buttons can be selected when using the Head Tracking feature

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#605]
### Description
For the My Sayings category, we have disabled the 'Remove Category' button so that users cannot remove it. However, the button can still be selected and the category removed by using the cursor for head tracking. This is also true of the 'Show Category' and 'Edit Phrases' buttons when they are in the disabled state.

### Steps to Reproduce
1. With head tracking turned ON
2. Navigate to the Settings > Categories and Phrases screen
3. Locate and select the '123' keypad category
4. Note that the 'Edit Phrases' button is disabled
5. Hover the head tracking cursor over the button until it is selected

**Expected behavior**
Nothing happens after you hover the head tracking cursor over the button long enough for it to be selected.

**Actual behavior**
Once the button is selected the user is transitioned to the edit category phrases screen for the keypad, which should not be possible.

**Device Information**
 - Device: iPad, iPhone
 - OS: iOS 14, 15

**Comment by rowildcard** [comment]
Test verified on:
iPhone 12 Pro Max, iOS 15
iPad 9th gen, iOS 15
landscape & portrait

Try to select disabled buttons with head tracking:
- 123 > Edit Phrases ✅ 
- My Sayings > Remove Category ✅ 
- Recents > Edit Phrases ✅ 
- Keyboard > save button ✅ 
- Main screen > pagination ✅
