### ISSUE TITLE
iOS 14 - Currently Selected Category Does Not Update With Changes to Phrase(s)

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#607]
## Description
The currently selected category on the main screen when the edit flow is initiated for that category does not update immediately as the user returns to the main screen. This is true of the phrases in the selected category, and sometimes the name of the category as well.

### Steps to Reproduce:
1. On an iOS 14 device
2. Scroll the Main Screen to the 'Basic Needs' category
3. With 'Basic Needs' currently selected, tap the settings button
4. Navigate to 'Categories and Phrases' and select 'Basic Needs'
5. Tap the 'Edit Phrases' button
6. Tap the 'I want to sit up' phrase
7. Rename the phrase; for example to 'Hello'
8. Return to the Main Screen

**Expected behavior**
When you return to the main screen, 'Basic Needs' is still the selected category and the phrase cell is updated to reflect the change; from "I want to sit up" to "Hello". 

**Actual behavior**
The phrase cell maintains the original phrase instead of updating to reflect the new changes; tapping it will speak aloud the expected phrase. In this state, the same behavior is seen of the category title cell. Navigating and coming back to the category with the carousel or rotating the device will update the screen to reflect the expected changes.

### Recording:

https://user-images.githubusercontent.com/34660497/165560818-daf7489b-d085-4a7e-80b8-eb812261c395.mov

**Device Information**
 - Device: iPhone X; iPhone 8 Plus
 - OS: 14.2; 14.8.1

**Comment by SashankPatel** [comment]
Since this is iOS specific, decided to try to fix for 1.4.

**Comment by SashankPatel** [comment]
Verified on iPhone 8 iOS 14 simulator, iPhone 11 iOS 15.4
- Verified modifying phrase updates in settings and main screen if the category is visible.
- Verified modifying category title on Settings screen and Main Screen
    ISSUE: @Clstroud : Noticed the Category title did not update on the main screen.
