### ISSUE TITLE
Mixpanel Integration: General Analytics 

### ISSUE THREAD

**Issue by Ly-Kyli** [willowtreeapps/eyespeak-ios#613]
The purpose of this ticket is to implement Mixpanel Integration so that we can track events related to general usage.

**Acceptance Criteria:** 
- All events tracked are not tied to user private information
- Events track meets apple requirements to maintain [App Store Privacy disclosure](https://developer.apple.com/app-store/app-privacy-details/#linked-data) of "Data Not Linked to You"

**Events captured includes:**
1. Preset Category/Phrase Selection
    - When a preset category is selected
    - When a preset phrase is selected from a preset category 
3. Keyboard from main page
    - When keyboard opens 
    - When the speak option is selected
    - When favorite is selected
4. Timing and Sensitivity Tracking
     - Hover time changed 
     - Cursor Sensitivity Changed 
5. Usage events
     - When application is opened
     - When application is backgrounded
     - When application is is closed
6. Device Orientation
     - Super property for each event showing device orientation

     
Links:
- [Tracking Plan Provided by Analytics Team]- See WT Confluence

**Comment by CananArikan** [comment]
Hey @Ly-Kyli, @jsmorgan42, @SashankPatel,

@rowildcard, @rhsalas3, and I have some questions below. 

1. Preset Category/Phrase Selection

  - We don't have implementation of selecting a preset category, there is one in the Mixpanel Tracking Plan sheet. Do we want to implement it?
  - Selection method is not appearing for our events in the Mixpanel. Is it still something we intend to include?

2. Keyboard from main page

- We track when favorite is selected, do we want to track when it is deselected?

3. Usage events

- When application is closed, we don't have this implementation and also nothing specified in the Mixpanel Tracking Plan sheet. Do we still want an event for this?
- We have implementation of `App Backgrounded`, but it is not specified in the sheet. Should we include it in the sheet?
