### ISSUE TITLE
Crash - iOS 14 - Occurs when adding the very first phrase to an empty My Sayings category

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#616]
## Description:
There is a crash that occurs when you add the very first phrase to the My Sayings category. I have seen it occur during different scenarios of editing category names and ordering  but have not been able to nail down the exact few steps. However, the steps performed in the recording below do tend to get results if done exactly.

### Steps to Reproduce:
1. Install the app
2. launch the app and turn off head tracking (for convenience)
3. Navigate to Settings > Categories and Phrases
4. Hide the 'General' category (it should now be at the end of the list)
5. Remove (delete) the 'Basic Needs' category.
6. Remove (delete) the 'Personal Care' category.
7. Add 5 new custom categories
8. Your categories should be in the following order:
    - Conversation
    - Environment
    - 123
    - My Sayings
    - Recents
    - Custom 1
    - Custom 2
    - Custom 3
    - Custom 4
    - Custom 5
    - General (hidden)
9. Hide 'Custom 5' 
10. Hide 'Custom 4'
11. Add a new category, as a duplicate with the same name as 'Custom 5'
12. Your categories should now be in the following order:
    - Conversation
    - Environment
    - 123
    - My Sayings
    - Recents
    - Custom 1
    - Custom 2
    - Custom 3
    - Custom 5 (the duplicate)
    - General (hidden)
    - Custom 4 (hidden)
    - Custom 5 (hidden)
13. Return to the main screen
14. Locate the 'Custom 5' category (our duplicate); should be an empty category
15. Add a single new phrase using the empty state "Add Phrase" button
16. Scroll to the My Sayings category; should be empty
17. Add a single new phrase using the empty state "Add Phrase" button 

**Expected behavior**
All is well, no crash occurs after you select the check mark add button while adding the very first phrase to My Sayings.

**Actual behavior**
When adding the very first phrase to the My Sayings category, using the empty state 'Add Phrase' button, a crash occurs as soon as you tap on the check mark add button (on the keyboard).

### Screen Recording:

https://user-images.githubusercontent.com/34660497/165813023-da88db89-45af-4fd1-a0c6-f70ac2a01e57.mov

**Device Information**
 - Devices: iPhone X on iOS 14.2

**Comment by SashankPatel** [comment]
Was able to reproduce on simulator with iPhone 8 iOS 14.4 with the following steps:
1.) Install the app fresh.
2.) Tap on the Left page button to navigate to the "123" category
3.) Tap on the Right page button to go to My Sayings.
4.) Add a phrase in my sayings via the keyboard and the app crashes.
