### ISSUE TITLE
`Hey Vocable` shortcut is not navigating to the listening mode screen right after enabling listening mode

### ISSUE THREAD

**Issue by CananArikan** [willowtreeapps/eyespeak-ios#644]
**Description**
`Hey Vocable` shortcut is not navigating to the listening mode screen right after enabling listening mode. But, when we manually navigate to the Listen category at the main screen, after app starts to listen, then `Hey vocable` shortcut works as expected. 

Update: Also, when you close and re-open the app after enabling listening mode the `Hey Vocable` shortcut does not work until you manually navigate to the Listen category.

**Steps To Reproduce**

1. Restart the app
2. Go to the Settings
3. From Listening Mode, grant accesses 
4. Say the `Hey vocable` shortcut at the Settings Screen or Main Screen

**Expected behavior**
`Hey Vocable` shortcut is navigating to the listening mode screen.
After closing and restarting the app, `Hey Vocable` shortcut will navigate use to the listening mode screen

**Actual behavior**
`Hey Vocable` shortcut is not navigating to the listening mode screen.

**Device Information**
iPad Pro - Test Device - iOS 15.3.1

**Build**
1.4.1-1

**Screenshots**

https://user-images.githubusercontent.com/100222793/167493073-01188ecf-185c-4a2e-a2a1-87cf13c744b7.mov

**Comment by moyerr** [comment]
I believe this is obsoleted by #642, as I am no longer able tor reproduce the issue. Can you confirm @CananArikan?

**Comment by CananArikan** [comment]
@moyerr I am able to reproduce this issue, I have updated the steps to reproduce.
