### ISSUE TITLE
Listen Category missing from Settings > Categories list when turned off

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#646]
### Description: 
There are 2 flows for turning off listening mode:
1. Settings > 'Listening Mode' setting; OR 
2. Settings > 'Categories and Phrases' > edit the 'Listen' category.

When using flow `2` the category remains in the list and behaves as any other category would when hidden. However, when using flow `1` the category is removed from the list of categories. The 'Listen' category should remain in the list of categories even when turned off from within the Settings > 'Listening Mode' setting.

Update: currently it is expected behavior for flow `2`. But I think the team should rethink the flow given that toggling the listen mode behaves differently on this screen, than when editing other categories. Per the comment discussion on this issue, it seems to make the most sense to just keep flow `1` and not even list the 'Listen' category from w/in the Categories list screen.

**Steps to Reproduce:**
1. From the main screen, navigate to Settings > 'Listening Mode'. 
2. Tap on the 'Listening Mode' toggle button to turn the feature OFF.
3. Return to Settings
4. Tap 'Categories and Phrases'
5. Note that the 'Listen' category is not in the list.

**Expected behavior:**
After turning off Listen Mode from within Settings > 'Listen Mode', a user should still be able to re-enable listening mode from Settings > Categories and Phrases > edit 'Listen' category.

**Actual behavior:**
After turning off Listen Mode from within Settings > 'Listen Mode' the 'Listen' category is removed from the list of categories. 

-----

**Device Information:**
Latest build on develop as of 05.10.2022

**Comment by rhsalas3** [comment]
@SashankPatel 

Tagging you hear to help make you aware that I created this bug ticket.

**Comment by rhsalas3** [comment]
@SashankPatel 

I just realized that the 'Listen' category would also be removed from the list once the user exists the 'Categories' screen. Now I understand this to be expected behavior, but wonder if it is still a more pleasant user experience to keep the 'Listen' category listed. It can be a jarring experience to turn it off from the Categories screen one minute, then it go "missing" the next time you look for it, since you're "conditioned" to edit categories from the list screen and only tapping "Remove Category" does the same behavior for the others. 🤔  🤔

**Comment by SashankPatel** [comment]
> @SashankPatel
> 
> I just realized that the 'Listen' category would also be removed from the list once the user exists the 'Categories' screen. Now I understand this to be expected behavior, but wonder if it is still a more pleasant user experience to keep the 'Listen' category listed. It can be a jarring experience to turn it off from the Categories screen one minute, then it go "missing" the next time you look for it, since you're "conditioned" to edit categories from the list screen and only tapping "Remove Category" does the same behavior for the others. 🤔 🤔

Yeah so when you toggle it off, the category should be removed from the main screen, but I think it should still be visible in Settings so you can turn it back on lol.  It should basically act like the Show Category toggle.  Its kinda weird that the setting is in two places.  Maybe we remove the category settings options from the edit view?

**Comment by rhsalas3** [comment]
> > @SashankPatel
> > I just realized that the 'Listen' category would also be removed from the list once the user exists the 'Categories' screen. Now I understand this to be expected behavior, but wonder if it is still a more pleasant user experience to keep the 'Listen' category listed. It can be a jarring experience to turn it off from the Categories screen one minute, then it go "missing" the next time you look for it, since you're "conditioned" to edit categories from the list screen and only tapping "Remove Category" does the same behavior for the others. 🤔 🤔
> 
> Yeah so when you toggle it off, the category should be removed from the main screen, but I think it should still be visible in Settings so you can turn it back on lol. It should basically act like the Show Category toggle. Its kinda weird that the setting is in two places. Maybe we remove the category settings options from the edit view?

I agree that it should act like the 'Show Category' toggle. As far as two places, I don't mind that actually. But since it's faster for head tracking to go into Settings > Listening Mode it makes sense to me to remove 'Listen' from the list of categories altogether. So I am down for reducing to one flow; being just Settings > Listening Mode.

**Comment by rhsalas3** [comment]
> > > @SashankPatel
> > > I just realized that the 'Listen' category would also be removed from the list once the user exists the 'Categories' screen. Now I understand this to be expected behavior, but wonder if it is still a more pleasant user experience to keep the 'Listen' category listed. It can be a jarring experience to turn it off from the Categories screen one minute, then it go "missing" the next time you look for it, since you're "conditioned" to edit categories from the list screen and only tapping "Remove Category" does the same behavior for the others. 🤔 🤔
> > 
> > 
> > Yeah so when you toggle it off, the category should be removed from the main screen, but I think it should still be visible in Settings so you can turn it back on lol. It should basically act like the Show Category toggle. Its kinda weird that the setting is in two places. Maybe we remove the category settings options from the edit view?
> 
> I agree that it should act like the 'Show Category' toggle. As far as two places, I don't mind that actually. But since it's faster for head tracking to go into Settings > Listening Mode it makes sense to me to remove 'Listen' from the list of categories altogether. So I am down for reducing to one flow; being just Settings > Listening Mode.

After a discussion w/in a Slack huddle, the team determined it would be best not to remove the 'Listen' category from the categories list so that a user can still re-order it. Therefore, we are sticking with the first idea for the fix; to make the toggle work the same as show/hide other categories.

**Comment by rhsalas3** [comment]
This has been tested and verified. It works like a charm 🌟  🤩  🌟 

Tested on iPhone 8 Plus (iOS 14.8.1) and an iPhone X (iOS 14.2)
