### ISSUE TITLE
First phrase selected in a category gets spoken twice

### ISSUE THREAD

**Issue by moyerr** [willowtreeapps/eyespeak-ios#666]
Steps to reproduce:

Prerequisite - _Ensure selection by head tracking is enabled_
 
1. Navigate to a category
2. Select a phrase using head-tracking

Expected result: The phrase is selected once and spoken once
Actual result: The phrase is selected twice and spoken twice

Not that this only happens for the first phrase selected in a category. All subsequent phrases selected are correctly spoken once. However, the process will repeat each time the user navigates to a new category.

Video:

https://user-images.githubusercontent.com/9791664/168833250-03a63af4-a97e-4fa6-bfad-4f63753462d5.MP4

**Comment by rhsalas3** [comment]
I started on `develop` and was able to reproduce the errant behavior. From there I switched over to the PR branch and confirmed the fixed behavior with the areas of emphasis that Robbie stressed. Everything looks good. I didn't find any bugs, using head-gaze or touch, for phrase selection via switching categories or pages w/in a category. I also tested out the pagination on the Categories list and Category Details > Edit Phrases screens. I'm confident that this is a good fix. 

- [x] Phrase selection via head-gaze AND touch
- [x] Phrase selection after switching categories
- [x] Phrase selection after changing pages within a category
- [x] Multiple page changes (e.g. pressing the back button numerous times to cycle through the pages)

Devices I used for testing:
- iPhone 8 Plus - 14.8.1
- iPhone X - 14.2
- iPad Pro - 15.3.1
