### ISSUE TITLE
Vocable Release v1.4.1 - Listen Mode

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#668]
As a team we want to release the Listen Mode feature, as version 1.4.1.

#### Features Implemented & Bugs Fixed for this Release
- placeholder

------

### Checklist:
- [ ] Remaining work to complete: 
    - [x] #666 
    - [x] Identify flow where Siri/Dictation permissions error occurs for listening mode; update copy
        - [x] #688
    - [ ] Update website to include instructional video on engaging in Listening Mode; stopgap for not having tutorial
        - [x] #689 
- [x] Cut release branch - `release/1.4.1`
- [x] Complete release testing
    - [x] Regression testing - manual ([Kiwi](https://vocable.wtadev.com/accounts/login/?next=/plan/5/vocable-ios-q1-2022#testcases)) and automated tests
        - [x] iPhone - iOS 14
        - [x] iPhone - iOS 15
        - [x] iPad - iOS 15
    - [ ] Fix bugs found during regression:
        - [ ] ??
        - [ ] ??
    - [ ] Confirm fixed bugs from previous release; triage persisting bugs
        - [x] #601 
        - [x] #602 
        - [x] #605   
    - [x] Localization testing
       - [x] Put the strings in the app; English copy is confirmed and integrated
    - [x] Voice feature flag - confirm feature is turned ON
    - [ ] Confirm upgrade from 1.4 to 1.4.1 maintains app data/settings
- [x] Identify release candidate build number for AppStore review submittal
- [x] Submit release candidate for AppStore review.
- [x] Rejoice!!

**Comment by rhsalas3** [comment]
@SashankPatel 

I went ahead and created this ticket to track our progress for the 1.4.1 release; as we did for 1.4.

**Comment by SashankPatel** [comment]
Closing out, 1.4.1 was released to the public.
