### ISSUE TITLE
Listen Mode - `Share with Developer` function should be updated after each new phrase

### ISSUE THREAD

**Issue by CananArikan** [willowtreeapps/eyespeak-ios#677]
**Acceptance Criteria:**
- For each new phrase, user should get a refreshed `Share with Developer` button. 
- Pressing the "Share with Developer" button should share the most recent phrase spoken.
- We should refresh with a new phrase spoken, even if it would result in the same responses (i.e. subsequent Yes/No questions)

**Steps to Reproduce Actual Behavior**:
1) Go to Listen Mode
2) Say "Test"
3) As expected you will get the sounds complicated error
4) Tap on `Share with Developer`
5) As expected you will get the Thank you checkmark
6) Then, say "Happy"
7) Although you say a new phrase, the `Share with Developer` button is not updated to send the new phrase

**Comment by rhsalas3** [comment]
Tested and verified to be fixed.

Test device:
- iPhone 8 Plus
- iOS 14.8.1
