### ISSUE TITLE
[Listen] Repeated question gets no answers

### ISSUE THREAD

**Issue by rowildcard** [willowtreeapps/eyespeak-ios#679]
**Describe the bug**
In Listen, a question is spoken and answers are displayed. If the user selects Settings or Keyboard and returns to listen, repeating the same question will not display any answers. A different question must be asked. 

**To Reproduce**
1. Ask a question yes or no question.
    - the question appears in the output label.
    - possible answers appear on the screen.
2. You may or may not answer the question. 
3. Tap the Settings or keyboard button.
4. Tap the close button.
    - user is returned to the "Listen" category
    - the last question still appears in the output label. _I think this should be reset._ 
    - the answers are no longer displayed.
    - the "Listening..." message appears. 
5. Ask the same question again.
    **Expected**: The question reappears in the output label. Possible answers appear.
    **Actual**: The question reappears in the output label. No answers appear.

**Work Around**
Change categories or ask a different question.

**Screenshots**
Ask me and I'll demo the behavior for you. 

**Device Information**
 - Device: iPhone 12 Pro Max
 - OS: 15.0.2
 - TestFlight build 2781

**Comment by CananArikan** [comment]
I reproduced this issue on an iPad.

**Device Information**

- Device: iPad Pro
- iOS: 15.3.1
- TestFlight build 2781 and develop branch
