### ISSUE TITLE
Add Listening Mode Information and Instructional Video to Website

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#689]
### Description:
We need to inform Vocable users about the Listening Mode feature, and how to engage with the feature. We are planning to implement an onboarding flow into the app ( #97 ) that will instruct users, but until then we should include that information on the [Vocable site](https://www.vocable.app/), including a video on enabling the feature and device settings required for functionality.

[Vocable Website Repo](https://github.com/willowtreeapps/vocable-website) (not open source)

**Acceptance Criteria**:
- [ ] The Vocable site is updated to anounce/inform of the Listening Mode feature
- [ ] A short instructional video is included on the site, that demonstrates how to setup and engage with the feature

**Design**:
Designs are not available for this specific work but it may be helpful to reference the in-progress designs of the onboarding flow:
[Figma - Onboarding](https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=2199%3A0)

**Comment by Ly-Kyli** [comment]
Link to Video: https://vimeo.com/manage/videos/716902825

**Comment by SashankPatel** [comment]
Closing out the ticket, video was created and uploaded to Vimeo on Kyli's account.
