### ISSUE TITLE
Vocable iOS - CI Pipeline is broken

### ISSUE THREAD

**Issue by SashankPatel** [willowtreeapps/eyespeak-ios#715]
**Describe the bug**
Somehow the CI pipeline is broken.  There is an error about not having a valid dev profile.  This is prevents a build from being created and pushed up to testflight.

**To Reproduce**
- Merge in a PR

**Expected behavior**
CI pipeline passes

**Actual behavior**
CI Pipeline fails.
See following example: https://app.circleci.com/pipelines/github/willowtreeapps/vocable-ios/2277/workflows/2bafd13e-86e2-4f8c-b44f-f5ae11c3c0ba/jobs/2999

Error: There are no local code signing identities found.

**Comment by Clstroud** [comment]
The pipeline appears to be succeeding for now. Closing this until we see otherwise.
