### ISSUE TITLE
Investigate migration to Github Actions

### ISSUE THREAD

**Issue by Clstroud** [willowtreeapps/eyespeak-ios#732]
Attempt to migrate the current CircleCI pipeline to Github Actions.

Our localization workflow is no longer working due to branch protections on `develop`, which we don't want to remove. Github Actions should theoretically allow us to enforce localization exports such that they occur on PR branches exclusively, while also enforcing that step as a merge requirement.

**Comment by peterkos** [comment]
Goals:
- [x] Locally run w/ `act` (for devvin')
- [x] Get output closer to the current CircleCI output (specific test success vs. hunting around in the `test` step log)
- [x] Enforce localization exports on PRs (merge requirement)
- [x] Commit an updated .xliff l11n file

@Clstroud Is there anything I'm missing? Do we want to map over the other `fastlane` lanes as well (ex. `buildanddeploytotestflight`)?
